protected/controllers/BetController.php
<?php

class BetController extends Controller
{
	public $layout = 'bet';

	public function filters()
	{
		return array('rights');
	}

	public function allowedActions()
	{
		return '';
	}

	public function actionIndex()
	{
		$this->render('index');
	}

	public function actionQuestion($id)
	{
		$question = Utils::getOr404('Question',$id);
		$betForm = new BetForm;
		if(isset($_POST['BetForm'])){
			$this->newBet($question,$betForm);
		}
		$this->render('question',compact('question','betForm'));
	}

	private function newBet($question,$betForm)
	{
		$betForm->attributes=$_POST['BetForm'];
		if($betForm->validate()){
			$bet = new Bet;
			$bet->questionID = $question->id;
			$bet->point = $betForm->point;
			if($betForm->guess==1){
				$bet->trueUserID = Yii::app()->user->id;
			}elseif($betForm->guess==2){
				$bet->falseUserID = Yii::app()->user->id;
			}
			if($bet->save()){
				User::current()->losePoint($bet->point);
				Yii::app()->user->setFlash('success', '新下注成功，你花费了'.$bet->point.'个积分');
			}
			$this->refresh();
		}
	}

	public function actionRebet($id)
	{
		$bet = Utils::getOr404('Bet',$id);
		$guess = Utils::getParam('guess');
		if($guess==1 && !$bet->trueUserID){
			$bet->trueUserID = Yii::app()->user->id;
		}elseif($guess==2 && !$bet->falseUserID){
			$bet->falseUserID = Yii::app()->user->id;
		}else{
			throw new CHttpException(400,'非法请求');
		}
		if($bet->save()){
			User::current()->losePoint($bet->point);
			Yii::app()->user->setFlash('success', '对赌成功，你花费了'.$bet->point.'个积分');
		}
		$this->redirect(array('/bet/question','id'=>$bet->questionID));
	}

	public function actionMine()
	{
		$bets = User::current()->bets;
		$this->render('mine',compact('bets'));
	}
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout = 'column1';
	
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;
		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	public function actionConnect()
	{
		$service = Yii::app()->request->getQuery('service');
		if (isset($service)) {
			$authIdentity = Yii::app()->eauth->getIdentity($service);
			$authIdentity->redirectUrl = Yii::app()->user->returnUrl;
			$authIdentity->cancelUrl = $this->createAbsoluteUrl('site/login');

			if ($authIdentity->authenticate()) {
				$identity = new SUserIdentity($authIdentity);
				if ($identity->authenticate()) {
					Yii::app()->user->login($identity,0,true);
					$authIdentity->redirect(Yii::app()->user->returnUrl);
				}else {
					$authIdentity->cancel();
				}
			}
			$this->redirect(array('site/login'));
		}

		$this->render('login');	
	}

	public function actionRegister()
	{
		$model=new RegisterForm;

		if(isset($_POST['RegisterForm']))
		{
			$model->attributes=$_POST['RegisterForm'];
			if($model->validate()){
				$model->register();
				$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		// display the login form
		$this->render('register',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/layouts/bet.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span3">
	<div id="clock"></div>
	<h4>今日赌题</h4>
<?php $this->widget('QuestionList') ?>
</div>
<div class="span9">
	<div>
	<?php echo $content; ?>
	</div>
</div>

<?php $this->endContent(); ?>

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content" class="center">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <title><?php echo CHtml::encode($this->pageTitle); ?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="<?php echo Yii::app()->baseUrl.'/css/app.css' ?>" type="text/css">
	<script src="<?php echo Yii::app()->baseUrl.'/js/jqClock.js' ?>" type="text/javascript" charset="utf-8"></script>
	<script src="<?php echo Yii::app()->baseUrl.'/js/app.js' ?>" type="text/javascript" charset="utf-8"></script>

</head>

<body>

<div class="navbar navbar-static-top">
	<div class="navbar-inner">
	<div class="container-fluid">
	<a class="brand span3" href="#"><?php echo Yii::app()->name ?></a>
	<div class="nav-collapse collapse">
	<?php
	$this->widget('zii.widgets.CMenu', array(
		'items'=>array(
			array('label'=>'首页', 'url'=>'/index.php'),
			array('label'=>'我的', 'url'=>array('/bet/mine')),
			array('label'=>'管理','url'=>array('/admin'),'visible'=>Yii::app()->user->checkAccess('Manager')),
			array('label'=>'权限设置','url'=>array('/rights'),'visible'=>Yii::app()->user->checkAccess('Admin')),
			
			// array('label'=>'关于', 'url'=>array('/site/page', 'view'=>'about')),
		),
		'htmlOptions'=>array('class'=>'nav'),
		'id'=>'main-menu'
		));
	?>
	<ul class="pull-right nav">
		<?php if(!Yii::app()->user->isGuest): ?>
		<li><a>积分：<?php echo User::current()->point ?></a></li>
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">
				<?php echo User::current()->name ?> <span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
				<li><?php echo CHtml::link('设置','#') ?></li>
				<li><?php echo CHtml::link('我的主页','#') ?></li>
				<li class="divider"></li>
				<li><?php echo CHtml::link('退出',array('/site/logout')) ?></li>
			</ul>
		</li>
	<?php else: ?>
		<li><?php echo CHtml::link('登录',array('/site/login')) ?></li>
		<li><?php echo CHtml::link('注册',array('/site/register')) ?></li>
	<?php endif ?>
	</ul>
	</div><!--/.nav-collapse -->
	</div>
	</div>
</div>
<?php $this->widget('bootstrap.widgets.TbAlert', array(
	'block'=>true,
	'fade'=>true,
	'closeText'=>'&times;',
)); ?>
<div class="container-fluid">
	<div class="row-fluid">
		<?php echo $content ?>
	</div>
</div>

</body>
</html>